version: "3"

services:

  proxy:
    image: nginx
    volumes:
    - ./config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    - ./log:/var/log/nginx
    ports:
    - "8080:80"

  webapp1:
    image: mendhak/http-https-echo

  webapp2:
    image: mendhak/http-https-echo
