version: "3"

services:

  proxy:
    image: nginx
    volumes:
    - ./config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    - ./data:/data
    - ./log/proxy:/var/log/nginx
    ports:
    - "8080:80"

  webapp1:
    image: nginx
    volumes:
    - ./config/nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
    - ./data:/data
    - ./log/webapp1:/var/log/nginx

  webapp2:
    image: nginx
    volumes:
    - ./config/nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
    - ./data:/data
    - ./log/webapp2:/var/log/nginx
