version: "3"

services:

  loadbalancer:
    image: nginx
    volumes:
    - ./conf.d:/etc/nginx/conf.d:ro
    - ./data:/data
    - ./log-nginx:/var/log/nginx
    ports:
    - "8080:80"

  webapp1:
    image: jankysolutions/requestbin
    ports:
    - "8081:8000"
